# Generated by Django 3.1.7 on 2021-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Terengganu', max_length=100),
            preserve_default=False,
        ),
    ]
